// varieties.jsx
// Variety schema — the empty template used when creating a new variety.
// Actual variety data lives in user-config.js.

export var EMPTY_VARIETY = {
  id: null,
  fieldHoldWeeks: 0,
  fieldHoldHarvests: 1,
  name: "",
  cropType: "",
  sowMethod: "Direct",
  daysToGermination: "",
  daysToMaturity: "",
  transplantLeadWeeks: 0,
  harvestWindowWeeks: 1,
  bedPrepWeeks: 0,
  grownOnPlastic: false,
  gddBase: 40,
  gddToMaturity: "",
  frostHardy: false,
  requiredTag: "",
  harvestType: "whole",
  cuts: 1,
  regrowthWeeks: 0,
  yieldPer25ft: "",
  unitWeight: "",
  pricePerUnit: "",
  seedsPerFoot: "",
  rowSpacingIn: "",
  rowsPerBed: "",
  seeder: "",
  bedPrepTask: "",
  planningBufferDays: 3,
  harvestNotes: "",
  trayType: "",
  seedsPerCell: "",
  germTempMin: "",
  germTempIdeal: "",
  germTempMax: "",
};